{
 "title": "OpenTelemetry dotnet webapi  fiapCloudGame",
 "description": "fiapCloudGame",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "prom_ds", "query": "prometheus" },
   { "name": "loki_ds", "query": "loki" },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": {
     "query": "label_values(process_runtime_dotnet_assemblies_count,service_name)"
    }
   },
   {
    "name": "deployment_environment",
    "label": "Deployment Environment",
    "query": {
     "query": "label_values(process_runtime_dotnet_assemblies_count{service_name=\"$service_name\"},deployment_environment)"
    }
   },
   {
    "name": "service_version",
    "label": "Service version",
    "query": {
     "query": "label_values(process_runtime_dotnet_assemblies_count{service_name=\"$service_name\", deployment_environment=\"$deployment_environment\"},service_version)"
    }
   },
   {
    "name": "host_name",
    "query": {
     "query": "label_values(http_server_request_duration_seconds_count{service_name=\"$service_name\", deployment_environment=\"$deployment_environment\", service_version=\"$service_version\"},host_name)"
    }
   },
   {
    "name": "http_route",
    "query": {
     "query": "label_values(http_server_request_duration_seconds_count{service_name=\"$service_name\", deployment_environment=\"$deployment_environment\", service_version=\"$service_version\", host_name=~\"$host_name\"},http_route)"
    }
   },
   {
    "name": "http_response_status_code",
    "query": {
     "query": "label_values(http_server_request_duration_seconds_count{service_name=\"$service_name\", deployment_environment=\"$deployment_environment\", service_version=\"$service_version\", host_name=~\"$host_name\", http_route=~\"$http_route\"},http_response_status_code)"
    }
   },
   { "name": "top", "label": "Top", "query": "1, 5, 10" },
   { "name": "percentile", "query": "p95 : 0.95, p50 : 0.50" }
  ]
 },
 "panels": [
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Rates",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(${top}, \r\n    sum by (http_response_status_code) (rate(http_server_request_duration_seconds_count{service_name=\"${service_name}\", service_version=\"${service_version}\", deployment_environment=\"${deployment_environment}\", host_name=~\"${host_name}\", http_route=~\"${http_route}\", http_response_status_code=~\"${http_response_status_code}\"}[$__rate_interval]))\r\n)",
     "legendFormat": "{{http_response_status_code}}"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "heatmap",
   "description": "https://learn.microsoft.com/en-us/dotnet/core/diagnostics/built-in-metrics-aspnetcore#metric-httpserverrequestduration",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_bucket{service_name=\"${service_name}\", service_version=\"${service_version}\", deployment_environment=\"${deployment_environment}\", host_name=~\"${host_name}\", http_route=~\"${http_route}\", http_response_status_code=~\"${http_response_status_code}\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "RED", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Http Server requests Rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(${top}, \r\n    sum by (host_name,http_request_method,http_route,url_scheme,http_response_status_code) (rate(http_server_request_duration_seconds_count{service_name=\"${service_name}\", service_version=\"${service_version}\", deployment_environment=\"${deployment_environment}\", host_name=~\"${host_name}\", http_route=~\"${http_route}\", http_response_status_code=~\"${http_response_status_code}\"}[$__rate_interval]))\r\n)",
     "legendFormat": "{{http_request_method}} {{url_scheme}}://{{host_name}}{{http_route}}: {{http_response_status_code}}"
    }
   ]
  },
  {
   "title": "Http Server requests Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(${top}, \r\n    sum by(host_name, url_scheme, http_request_method, http_route, http_response_status_code, error_type) (rate(http_server_request_duration_seconds_count{service_name=\"${service_name}\", service_version=\"${service_version}\", deployment_environment=\"${deployment_environment}\", host_name=~\"${host_name}\", http_route=~\"${http_route}\", http_response_status_code!~\"[1-3]..\", http_response_status_code=~\"${http_response_status_code}\"}[$__rate_interval]))\r\n)",
     "legendFormat": "{{http_request_method}} {{url_scheme}}://{{host_name}}{{http_route}}: {{http_response_status_code}} {{error_type}}"
    }
   ]
  },
  {
   "title": "Http Server requests Durations ($percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "repeat": "percentile",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk($top, \r\n    histogram_quantile(${percentile:value}, \r\n        sum(rate(http_server_request_duration_seconds_bucket{service_name=\"$service_name\", deployment_environment=\"$deployment_environment\", host_name=~\"${host_name}\", http_route=~\"${http_route}\", http_response_status_code=~\"${http_response_status_code}\"}[$__rate_interval])) by (le, http_request_method, url_scheme, host_name, http_route, http_response_status_code)\r\n    )\r\n)",
     "legendFormat": "{{http_request_method}} {{url_scheme}}://{{host_name}}{{http_route}}: {{http_response_status_code}}"
    }
   ]
  },
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_runtime_dotnet_cpu_usage_ratio{service_name=\"$service_name\", deployment_environment=\"$deployment_environment\"}[1m])",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_runtime_dotnet_gc_heap_size_bytes{service_name=\"$service_name\", deployment_environment=\"$deployment_environment\"}",
     "legendFormat": "Memory Usage ({{generation}})"
    }
   ]
  },
  {
   "title": "Process Threads",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_runtime_dotnet_thread_pool_threads_count{service_name=\"$service_name\", deployment_environment=\"$deployment_environment\"}",
     "legendFormat": "Process Threads"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Application Logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"fcg-api\"} |= ``"
    }
   ]
  }
 ]
}